active_walker:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50  
  

    # Effort Controllers ---------------------------------------
    rear_left_wheel_effort_controller:
        type: effort_controllers/JointEffortController
        joint: rear_left_wheel_joint
        pid: {p: 100.0, i: 0.1, d: 10.0}
    rear_right_wheel_effort_controller:
        type: effort_controllers/JointEffortController
        joint: rear_right_wheel_joint
        pid: {p: 100.0, i: 0.1, d: 10.0}