## USB port
port: /dev/walker_imu_sensor


##### Calibration ####
### accelerometer
accel_x_min: -260.86
accel_x_max: 260.25
accel_y_min: -260.74
accel_y_max: 260.13
accel_z_min: -260.13
accel_z_max: 260.74

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [374.568, -193.203, -521.161]
magn_ellipsoid_transform: [[0.984002, -0.00715089, -0.0102216], [-0.00715089, 0.936168, 0.0203967], [-0.0102216, 0.0203967, 0.98319]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -0.01
gyro_average_offset_y: -0.01
gyro_average_offset_z: -0.01
